#! /bin/bash
#
# hooks/pre-up/applications
#
# Standard applications I want installing. Not really to do with dot-files, but
# part of my standard set-up, so it's reasonable to hook them in here.


# Nala first, so I can use that to install other packages:
if ! command -v nala > /dev/null
then
  echo Trying to install nala
  sudo apt install nala < /dev/tty
fi

# List of packages to install:
pkg=""

# Commands whose package name is identical to the command name; remove anything
# under ~/ from $PATH before searching it, to avoid matching any of my wrapper
# scripts, the existence of which doesn't indicate that the underlying command
# they are wrapping has been installed:
PATH=$(echo "$PATH" | tr : "\n" | grep -v ^$HOME | paste -sd :)
for cmd in \
    waypipe nvi plocate ncal units tig pgcli curl lynx zathura ffmpeg an
do
  if ! command -v $cmd > /dev/null
  then
    echo Trying to install $cmd.
    pkg="$pkg $cmd"
  fi
done

if ! command -v sshtunnel > /dev/null
then
  echo Trying to install python3-sshtunnel.
  pkg="$pkg python3-sshtunnel"
fi

if ! command -v convert > /dev/null
then
  echo Trying to install imagemagick.
  pkg="$pkg imagemagick"
fi

if ! command -v pdfjam > /dev/null
then
  echo Trying to install texlive-extra-utils.
  pkg="$pkg texlive-extra-utils"
fi

if ! command -v imgsize > /dev/null
then
  echo Trying to install libimage-size-perl.
  pkg="$pkg libimage-size-perl"
fi

if ! command -v /usr/bin/cpanm > /dev/null
then
  echo Trying to install cpanminus.
  pkg="$pkg cpanminus"
fi

# Wordlists:
for lang in british american
do
  for size in '' '-huge'
  do
    if [ ! -f /usr/share/dict/$lang-english$size ]
    then
      dict=w$lang$size
      echo Trying to install $dict.
      pkg="$pkg $dict"
    fi
  done
done

# Graphical applications, only to install if running directly in a desktop
# environment:
if [ "$XDG_CURRENT_DESKTOP" ]
then

  if ! command -v quodlibet > /dev/null
  then
    echo Trying to install quodlibet.
    pkg="$pkg quodlibet gstreamer1.0-plugins-bad libmodplug1"
  fi

  for cmd in gimp inkscape scribus libreoffice gnumeric
  do
    if ! command -v $cmd > /dev/null
    then
      echo Trying to install $cmd.
      pkg="$pkg $cmd"
    fi
  done
fi

# Perl documenation
if ! perldoc -V &> /dev/null
then
  echo Trying to install perl-doc.
  pkg="$pkg perl-doc"
fi

# Perl modules, used by commands in ~/bin/:
for module in data-printer
do
  module=lib$module-perl
  if [ ! -d /usr/share/doc/$module ]
  then
    echo Trying to install $module.
    pkg="$pkg $module"
  fi
done

# Install anything identiied by the above:
if [ "$pkg" ]
then
  sudo nala install $pkg < /dev/tty

  # If nvi has been installed then make it be used for the vi command:
  if [[ $pkg =~ (^| )nvi( |$) ]]
  then
    sudo echo nvi installed
    sudo update-alternatives --set vi /usr/bin/nvi
  fi
fi
