#! /bin/sh
#
# hooks/pre-up/locale
#
# The Bash config tries to use the en_GB.utf8 locale. If that isn't available,
# try to install it:

if ! locale -a | grep -qFx en_GB.utf8
then
  echo Trying to install en_GB.utf8 locale.

  # By default apt prompts for confirmation and immediately exits; it appears
  # that inside this hook stdin has been redirected, so redirect it back to the
  # terminal:
  sudo apt install language-pack-en-base < /dev/tty
fi
