#! /bin/sh
#
# vim_packages
#
# Ensures external packages in Git submodules are installed, and generates Vim
# help tags for them.


git submodule update --init

for doc_dir in ~/.vim/pack/*/*/*/doc
do
  if [ ! -f "$doc_dir/tags" ]
  then
    ex -u NONE -c "helptags $doc_dir" -c q
  fi
done
